#---------------- IOP drivers embedded by the core -----------------#
# Only file I/O. Everything else is embedded by the module that needs it.
$(EE_EMBED_DIR)iomanx.c: $(PS2SDK)/iop/irx/iomanX.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ iomanX_irx

$(EE_EMBED_DIR)filexio.c: $(PS2SDK)/iop/irx/fileXio.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ fileXio_irx

#------------------ Files embedded by Athena modules ------------------#
# MODULE_EMBED, MODULE_EMBED_PATH_<symbol> and MODULE_EMBED_BUILD_<symbol> come
# from Makefile.modules (module.json "embed" / "embed_irx"). Each file becomes
# <symbol>[] / size_<symbol>. Files built from this repository are rebuilt
# when any source in their directory changes.

define MODULE_EMBED_RULE
$(EE_EMBED_DIR)$(1).c: $(MODULE_EMBED_PATH_$(1)) | $(EE_EMBED_DIR)
	$$(BIN2S) $$< $$@ $(1)
endef

define MODULE_EMBED_BUILD_RULE
$(MODULE_EMBED_PATH_$(1)): $(filter-out %.irx %.elf %.o %.d,$(wildcard $(MODULE_EMBED_BUILD_$(1))/*.*))
	$$(MAKE) -C $(MODULE_EMBED_BUILD_$(1))
endef

$(foreach e,$(MODULE_EMBED),$(eval $(call MODULE_EMBED_RULE,$(e))))
$(foreach e,$(MODULE_EMBED),$(if $(MODULE_EMBED_BUILD_$(e)),$(eval $(call MODULE_EMBED_BUILD_RULE,$(e)))))
