#-------------------- Embedded IOP Modules ------------------------#
$(EE_EMBED_DIR)iomanx.c: $(PS2SDK)/iop/irx/iomanX.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ iomanX_irx

$(EE_EMBED_DIR)filexio.c: $(PS2SDK)/iop/irx/fileXio.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ fileXio_irx

$(EE_EMBED_DIR)sio2man.c: $(PS2SDK)/iop/irx/sio2man.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ sio2man_irx

$(EE_EMBED_DIR)mcman.c: $(PS2SDK)/iop/irx/mcman.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ mcman_irx

$(EE_EMBED_DIR)mcserv.c: $(PS2SDK)/iop/irx/mcserv.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ mcserv_irx

$(EE_EMBED_DIR)padman.c: $(PS2SDK)/iop/irx/padman.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ padman_irx

$(EE_EMBED_DIR)usbd.c: $(PS2SDK)/iop/irx/usbd.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ usbd_irx

$(EE_EMBED_DIR)bdm.c: $(PS2SDK)/iop/irx/bdm.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ bdm_irx

$(EE_EMBED_DIR)bdmfs_fatfs.c: $(PS2SDK)/iop/irx/bdmfs_fatfs.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ bdmfs_fatfs_irx

$(EE_EMBED_DIR)usbmass_bd.c: $(PS2SDK)/iop/irx/usbmass_bd.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ usbmass_bd_irx

$(EE_EMBED_DIR)cdfs.c: $(PS2SDK)/iop/irx/cdfs.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ cdfs_irx

$(EE_EMBED_DIR)poweroff.c: $(PS2SDK)/iop/irx/poweroff.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ poweroff_irx

iop_modules/freeram/freeram.irx: iop_modules/freeram
	$(MAKE) -C $<

$(EE_EMBED_DIR)freeram.c: iop_modules/freeram/freeram.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ freeram_irx

#------------- IOP Modules embedded by Athena modules -------------#
# MODULE_IRX, MODULE_IRX_PATH_<name> and MODULE_IRX_BUILD_<name> come from
# Makefile.modules. IRX built from this repository are rebuilt when any file
# in their directory changes.

define MODULE_IRX_EMBED_RULE
$(EE_EMBED_DIR)$(1).c: $(MODULE_IRX_PATH_$(1)) | $(EE_EMBED_DIR)
	$$(BIN2S) $$< $$@ $(1)_irx
endef

define MODULE_IRX_BUILD_RULE
$(MODULE_IRX_PATH_$(1)): $(filter-out %.irx %.elf,$(wildcard $(MODULE_IRX_BUILD_$(1))/*.*))
	$$(MAKE) -C $(MODULE_IRX_BUILD_$(1))
endef

$(foreach irx,$(MODULE_IRX),$(eval $(call MODULE_IRX_EMBED_RULE,$(irx))))
$(foreach irx,$(MODULE_IRX),$(if $(MODULE_IRX_BUILD_$(irx)),$(eval $(call MODULE_IRX_BUILD_RULE,$(irx)))))

#-------------------- Embedded EE Modules ------------------------#

ee_modules/loader/loader.elf: ee_modules/loader
	$(MAKE) -C $<

$(EE_EMBED_DIR)loader_elf.c: ee_modules/loader/loader.elf | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ loader_elf

$(EE_EMBED_DIR)quicksand_regular.c: assets/fonts/Quicksand-Regular.ttf | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ quicksand_regular
