#ifndef ATHENA_MODULE_H
#define ATHENA_MODULE_H

/*
 * Native module registry. This header must stay free of any scripting
 * runtime type: it is shared by the QuickJS runtime and by pure C
 * applications (RUNTIME=native). Bindings for QuickJS live in
 * src/runtime/quickjs/include/athena_js_module.h.
 *
 * The table itself is generated by tools/modules.js from the "native"
 * section of each module.json (src/generated/native_registry.c).
 */

#include <stdbool.h>

typedef struct {
    const char *id;               /* Module id, e.g. "thread" */
    void (*register_iop)(void);   /* Optional. Registers IRX drivers before the IOP is reset at boot. */
    int (*init)(void);            /* Optional. Called once at boot; < 0 aborts the boot. */
    void (*shutdown)(void);       /* Optional. Called in reverse order on exit. */
    void (*quiesce)(void);        /* Optional. Waits for background work before the runtime is torn down. */
    int (*stop_requested)(void);  /* Optional. Non-zero asks the running application to stop. */
} AthenaNativeModule;

#ifdef __cplusplus
extern "C" {
#endif

/* NULL-terminated, generated. */
extern const AthenaNativeModule athena_native_modules[];

void athena_modules_register_iop(void);
int athena_modules_init(void);
void athena_modules_shutdown(void);
void athena_modules_quiesce(void);
int athena_modules_stop_requested(void);
bool athena_module_enabled(const char *id);

#ifdef __cplusplus
}
#endif

#endif /* ATHENA_MODULE_H */
